# Generated by Django 3.2 on 2021-04-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=200)),
            ],
        ),
    ]
