# Generated by Django 3.2 on 2021-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_youtubeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeid',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubeid',
            name='videoID',
            field=models.TextField(),
        ),
    ]
