# Generated by Django 3.2 on 2021-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210412_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeid',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='youtubeid',
            name='videoID',
            field=models.CharField(max_length=100),
        ),
    ]
