# Generated by Django 3.2 on 2021-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210416_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotifyID',
            field=models.CharField(max_length=50),
        ),
    ]
