# Generated by Django 3.2 on 2021-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210416_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='spotifyID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
