# Generated by Django 3.2 on 2021-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210416_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotifyID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
