# Generated by Django 3.2 on 2021-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_artist_spotifyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotifyID',
            field=models.CharField(max_length=100),
        ),
    ]
